-- CRIAÇÃO DO BANCO DE DADOS 


CREATE TABLE ALUNO (
MATRICULA SERIAL PRIMARY KEY,
NOME VARCHAR(100),
UNIDADE VARCHAR(40),
TURMA VARCHAR (15),
EMAIL VARCHAR (60),
SENHA_EMAIL VARCHAR(15),
LOGIN_APP CHAR(4),
SENHA_R CHAR(10),
VIVADI CHAR(8),
ARVORE CHAR(11));


NOME VARCHAR(80)
SERIE VARCHAR(40)
UNIDADE VARCHAR(20)
EMAIL VARCHAR(80)
SENHA_EMAIL VARCHAR(20)
MATRICULA CHAR(4)
SENHA_APP CHAR(6)
SFB VARCHAR(80)
SENHA_SFB CHAR(6)
RICHMOND VARCHAR(80)
SENHA_R VARCHAR(20)
ARVORE_SENHA CHAR(5)
EVOLUCIONAL VARCHAR(15)
SENHA_EVO VARCHAR(15)
MEDALHEI VARCHAR(80)


INSERT INTO ALUNO (NOME,SERIE,UNIDADE,EMAIL,SENHA_EMAIL,MATRICULA,SENHA_APP,SFB,SENHA_SFB,RICHMOND,SENHA_R,ARVORE_SENHA,EVOLUCIONAL,SENHA_EVO,MEDALHEI)
VALUES ('ALIRIA SOPHIA FREITAS DINIZ','1ª Série A','VILA BESSA','aliria.diniz@sou.vilacolegio.com.br','mudar@1234','3257','160409','aliria.sophiafreitasdiniz.7','ddmmaa',	'NULL',	'NULL','NULL','9580886','vila@2024','aliria.diniz@sou.vilacolegio.com.br');												



SELECT * FROM ALUNO;

INSERT INTO ALUNO (MATRICULA, NOME, UNIDADE, TURMA, EMAIL, SENHA_EMAIL, LOGIN_APP, SENHA_R, VIVADI, ARVORE)
VALUES (1234, 'ANDERSON SOUSA', 'VILA SUL', '1 ANO', 'ANDERSON@TESTEVILA.COM', 'ANDERSON123', '1234', '1456', 'ABCD', 'AVCD');
