-- CRIAÇÃO DO BANCO DE DADOS 


CREATE TABLE ALUNO (
MATRICULA SERIAL PRIMARY KEY,
NOME VARCHAR(100),
UNIDADE VARCHAR(40),
TURMA VARCHAR (15),
EMAIL VARCHAR (60),
SENHA_EMAIL VARCHAR(15),
LOGIN_APP CHAR(4),
SENHA_R CHAR(10),
VIVADI CHAR(8),
ARVORE CHAR(11));


SELECT * FROM ALUNO;

INSERT INTO ALUNO (MATRICULA, NOME, UNIDADE, TURMA, EMAIL, SENHA_EMAIL, LOGIN_APP, SENHA_R, VIVADI, ARVORE)
VALUES (1234, 'ANDERSON SOUSA', 'VILA SUL', '1 ANO', 'ANDERSON@TESTEVILA.COM', 'ANDERSON123', '1234', '1456', 'ABCD', 'AVCD');
