


/*CREATE TABLE ALUNO (
MATRICULA SERIAL PRIMARY KEY,
NOME VARCHAR(100),
UNIDADE VARCHAR(40),
TURMA VARCHAR (15),
EMAIL VARCHAR (60),
SENHA_EMAIL VARCHAR(15),
LOGIN_APP CHAR(4),
SENHA_R CHAR(10),
VIVADI CHAR(8),
ARVORE CHAR(11));
*/


--- Criação da TABELA ALUNO

NOME VARCHAR(80)
SERIE VARCHAR(40)
UNIDADE VARCHAR(20)
EMAIL VARCHAR(80)
SENHA_EMAIL VARCHAR(20)
MATRICULA CHAR(4)
SENHA_APP CHAR(6)
SFB VARCHAR(80)
SENHA_SFB CHAR(6)
RICHMOND VARCHAR(80)
SENHA_R VARCHAR(20)
ARVORE_SENHA CHAR(5)
EVOLUCIONAL VARCHAR(15)
SENHA_EVO VARCHAR(15)
MEDALHEI VARCHAR(80)


												


--- INSERT DE TESTE 
SELECT * FROM ALUNO;

